
import {
    Box, Heading,
    Avatar,
    Center,
    Image,
    Flex,
    Text,
    Stack,
    Button,
    useColorModeValue,
    Grid,
    GridItem,
    SimpleGrid,
    Table,
    Thead,
    Tbody,
    Tfoot,
    Tr,
    Th,
    Td,
    TableCaption,
    TableContainer,
    Card
} from "@chakra-ui/react";
import Link from 'next/link'
import Head from 'next/head'


function BlogDetail({ product }) {

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Box pt="55px">
                <Text fontSize='xl'>{product?.data?.data?.get_course_info}</Text>
                <Text fontSize='md'>{product?.data?.data?.get_course_info}</Text>
            </Box>
        </>
    )
}

export async function getStaticProps({ params }) {
  const id = params.id;
  const res = await fetch(`https://www.learnsbuy.com/api/get_course_infox/${id}`);
  const product = await res.json();
  return {
    props: {
      product,
    },
  };
}

export async function getStaticPaths() {
  const url = `https://www.learnsbuy.com/api/all_cource_app/1`;
  const res = await fetch(url);
  const posts = await res.json();
  const paths = posts?.data?.get_course.map((post) => {
    return {
      params: { id: String(post.c_id) },
    };
  });

  return {
    paths,
    fallback: false,
  };
}

export default BlogDetail