
import {
    Box, Heading,
    Avatar,
    Center,
    Image,
    Flex,
    Text,
    Stack,
    Button,
    useColorModeValue,
    Grid,
    GridItem,
    SimpleGrid,
    Table,
    Thead,
    Tbody,
    Tfoot,
    Tr,
    Th,
    Td,
    TableCaption,
    TableContainer,
    Card
} from "@chakra-ui/react";
import Link from 'next/link'
import Head from 'next/head'


function Blog({ users }) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Box pt="35px">
                <Text fontSize='xl'>ดึงข้อมูล getServerSideProps</Text>
                <Card p="10px">
                    <TableContainer>
                        <Table variant='simple'>
                            <Tbody>
                                {users?.data?.get_course?.map((post) => (
                                    // <li key={post.id}>{post.name}</li>
                                    <Tr key={post.c_id}>
                                        <Td isNumeric>
                                            <Link href={'/blog/'+post.c_id}>
                                                Go
                                            </Link>
                                        </Td>
                                        <Td></Td>
                                    </Tr>
                                ))}
                            </Tbody>
                        </Table>
                    </TableContainer>
                </Card >
            </Box>
        </>
    )
}

export async function getServerSideProps() {

    const res = await fetch(`https://www.learnsbuy.com/api/all_cource_app/1`)
    const users = await res.json()

    return { props: { users } }

}

export default Blog