import Head from 'next/head'
import { Inter } from '@next/font/google'
import "react-responsive-carousel/lib/styles/carousel.min.css"; // requires a loader
import { Carousel } from 'react-responsive-carousel';
import NaviTop from '@/components/NaviTop/';
import { FcAssistant, FcDonate, FcInTransit } from 'react-icons/fc';
import { Box,Table,
  Thead,
  Tbody,
  Tfoot,
  Tr,
  Th,
  Td,
  TableCaption,
  TableContainer, Card, Flex, Spacer, Stack, SimpleGrid, Icon, Text , Center } from "@chakra-ui/react";

  import img1 from '@/public/img/img_1.jpg'
  import img2 from '@/public/img/img_2.jpg'
  import img3 from '@/public/img/img_3.jpg'

const Feature = ({ icon, title }: { icon: string, title: string } ) => {
  return (
    <Stack>
      <Center>
      <Flex alignItems="center"
        w={16}
        h={16}
        align={'center'}
        justify={'center'}
        color={'white'}
        rounded={'full'}
        bg={'gray.100'}
        mb={1}>
        {icon}
      </Flex>
      </Center>
      <Center>
      <Text fontSize='xs' alignItems="center" fontWeight={600}>{title}</Text>
      </Center>
    </Stack>
  );
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box pt="35px">
      <Flex>
        <Box>
        <Text fontSize='xl'>คุณ Kim Kundad</Text>
        </Box>
        <Spacer />
        <Flex direction="column">
        <Text fontSize='md' color="gray.600">ยอดเงินคงเหลือ</Text>
        <Text fontSize='xl'>5,200</Text>
        </Flex>
      </Flex>
      <Card>
      <SimpleGrid columns={{ base: 3, md: 3 }} spacing={10} p={2}>
        <Feature
          icon={<Icon as={FcAssistant} w={10} h={10} />}
          title={'ติดต่อเรา'}
        />
        <Feature
          icon={<Icon as={FcDonate} w={10} h={10} />}
          title={'เครดิต '}
        />
        <Feature
          icon={<Icon as={FcInTransit} w={10} h={10} />}
          title={'จัดส่ง'}
        />
      </SimpleGrid>
      </Card>
      <Text fontSize='xl' mt="10px">แยก Components</Text>
      <Box>
        <NaviTop title={'เครดิต '} icon={<Icon as={FcInTransit} w={10} h={10} />} />
      </Box>
      <Text fontSize='xl' mt="10px">โปรโมชั่น</Text>
      <Card mt="10px">
      {/* https://www.npmjs.com/package/react-responsive-carousel */}
        <Carousel showArrows={true} autoPlay={true} showThumbs={false} infiniteLoop={true} >
                <div>
                    <img src={img1.src} />
                </div>
                <div>
                    <img src={img2.src} />
                </div>
                <div>
                    <img src={img3.src} />
                </div>
        </Carousel>
      </Card>
      <Text fontSize='xl' mt="10px">ธุรกรรมล่าสุด</Text>
      <Card mt="10px">
      {/* https://chakra-ui.com/docs/components/table */}
        <TableContainer>
          <Table variant='simple'>
            <TableCaption>Imperial to metric conversion factors</TableCaption>
            <Thead>
              <Tr>
                <Th>To convert</Th>
                <Th>into</Th>
                <Th isNumeric>multiply by</Th>
              </Tr>
            </Thead>
            <Tbody>
              <Tr>
                <Td>inches</Td>
                <Td>millimetres (mm)</Td>
                <Td isNumeric>25.4</Td>
              </Tr>
              <Tr>
                <Td>feet</Td>
                <Td>centimetres (cm)</Td>
                <Td isNumeric>30.48</Td>
              </Tr>
              <Tr>
                <Td>yards</Td>
                <Td>metres (m)</Td>
                <Td isNumeric>0.91444</Td>
              </Tr>
            </Tbody>
            <Tfoot>
              <Tr>
                <Th>To convert</Th>
                <Th>into</Th>
                <Th isNumeric>multiply by</Th>
              </Tr>
            </Tfoot>
          </Table>
        </TableContainer>
      </Card>

      </Box>
    </>
  )
}
